[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci --prefix dashboard"]

[phases.build]
cmds = ["npm run build --prefix dashboard"]

[start]
cmd = "npm run start --prefix dashboard"
