[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd dashboard && npm install"]

[phases.build]
cmds = ["cd dashboard && npm run build"]

[start]
cmd = "cd dashboard && npm run start"
